export const jobCategories = [
  { id: "1", category: "Pet Sitting" },
  { id: "2", category: "House Sitting" },
  { id: "3", category: "Gardening" },
  { id: "4", category: "Home Cleaning" },
  { id: "5", category: "Delivery Services" },
  { id: "6", category: "Mystery Shopping" },
  { id: "7", category: "Online Surveys" },
  { id: "8", category: "Product Testing" },

  { id: "9", category: "Web Development" },
  { id: "10", category: "App Development" },
  { id: "11", category: "Software Testing" },
  { id: "12", category: "Digital Marketing" },
  { id: "13", category: "SEO Optimization" },
  { id: "14", category: "Social Media Management" },
  { id: "15", category: "Content Creation" },
  { id: "16", category: "Video Editing" },
  { id: "17", category: "Graphic Design" },
  { id: "18", category: "UX/UI Design" },
  { id: "19", category: "Illustration" },
  { id: "20", category: "Copywriting" },
  { id: "21", category: "Proofreading" },
  { id: "22", category: "Transcription Services" },
  { id: "23", category: "Translation Services" },

  { id: "24", category: "Freelance Writing" },
  { id: "25", category: "Technical Writing" },
  { id: "26", category: "Blogging" },
  { id: "27", category: "Ghostwriting" },
  { id: "28", category: "Copyediting" },
  { id: "29", category: "Scriptwriting" },

  { id: "30", category: "Photography" },
  { id: "31", category: "Videography" },
  { id: "32", category: "Voice Over" },
  { id: "33", category: "Animation" },
  { id: "34", category: "Music Composition" },
  { id: "35", category: "Podcast Editing" },
  { id: "36", category: "Creative Consulting" },

  { id: "37", category: "Tutoring" },
  { id: "38", category: "Curriculum Development" },
  { id: "39", category: "Online Course Creation" },
  { id: "40", category: "Educational Consulting" },
  { id: "41", category: "Test Prep Coaching" },

  { id: "42", category: "Virtual Assistance" },
  { id: "43", category: "Data Entry" },
  { id: "44", category: "Customer Support" },
  { id: "45", category: "Technical Support" },
  { id: "46", category: "Bookkeeping" },
  { id: "47", category: "Event Planning" },
  { id: "48", category: "Travel Planning" },
  { id: "49", category: "Research Assistance" },

  { id: "50", category: "Medical Transcription" },
  { id: "51", category: "Telehealth Consulting" },
  { id: "52", category: "Fitness Coaching" },
  { id: "53", category: "Nutrition Planning" },
  { id: "54", category: "Mental Health Counseling" },
  { id: "55", category: "Handmade Crafts" },
  { id: "56", category: "Woodworking" },
  { id: "57", category: "Metalworking" },
  { id: "58", category: "Tailoring and Sewing" },
  { id: "59", category: "Jewelry Making" },
  { id: "60", category: "Carpentry" },
  { id: "61", category: "Market Research" },
  { id: "62", category: "Sales Consulting" },
  { id: "63", category: "Product Demonstration" },
  { id: "64", category: "Brand Ambassadorship" },
  { id: "65", category: "Affiliate Marketing" },
];
