export const reasons = [
  { id: 1, reason: "Found a job" },
  { id: 2, reason: "Poor user experience" },
  { id: 3, reason: "Irrelevant job listings" },
  { id: 4, reason: "Too many notifications" },
  { id: 5, reason: "Better alternatives available" },
  { id: 6, reason: "Privacy concerns" },
  { id: 7, reason: "Encountered spam or scams" },
  { id: 8, reason: "Limited job opportunities" },
  { id: 9, reason: "High data usage" },
  { id: 10, reason: "Excessive ads and in-app purchases" },
  { id: 11, reason: "App takes up too much storage space" },
  { id: 12, reason: "Lack of new features or updates" },
  { id: 13, reason: "Consistent negative reviews" },
  { id: 14, reason: "Redundancy with other job search methods or platforms" },
  { id: 15, reason: "Other" },
];
